import os
import pandas as pd

configfile: "workflows/config.yml"

include: "rules/drimseq.smk"
include: "rules/HUGOID_annotation.smk"

rule all:
    input:
        f"results/{config['run_name']}/DRIMSeq/genes_DTU.tsv",
        f"results/{config['run_name']}/DRIMSeq/transcripts_proportions.tsv",
        f"results/{config['run_name']}/DRIMSeq/StageR.tsv",
        f"results/{config['run_name']}/DRIMSeq/genes_DTU.csv",
        f"results/{config['run_name']}/DRIMSeq/transcripts_proportions.csv",
        f"results/{config['run_name']}/DRIMSeq/StageR.csv"
